### PR TITLE
Update and clean up project (dependencies and formatting)

### LINKED ISSUE #15: Error while building for android [com.android.tools.build:gradle version not available]
I have an error when I try to build for android:

`could not find any matches for com.android.tools.build:gradle:2.2.+ as no versions of com.android.tools.build:gradle are available.
Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml
         https://jcenter.bintray.com/com/android/tools/build/gradle/
     Required by:
         project :react-native-gps-state`

The library uses an old version of Gradle that is not available in the jcenter repository

` dependencies {
        classpath 'com.android.tools.build:gradle:2.2.+'
    }
`

## Environment
react-native: 0.57.2
react-native-gps-state: 0.1.2

Can you please remove that dependency?
The lib will simply be built using the parent project's Gradle version.

### PR DESCRIPTION
**Pull request by friederbluemle**
This PR contains various project cleanups and fixes (in separate commits).

The main change is in `android/build.gradle` - removing a bunch of unused/unnecessary dependencies and declarations, and making it easier for app projects to consume the library (plus optionally customize the support lib version).

If you want, I can extract the formatting fixes into a separate PR. Please let me know.

Resolves #15

### CODE REVIEW

**Comment by neuberoliveira** [comment]
What tool are you use for code formating, and its configs (tab, spaces,  size,.....), so i can keep it

**Comment by friederbluemle** [comment]
@neuberoliveira - For code formatting, I just opened the project in Android Studio with the default settings, then applied the formatter, fixing the mix of tabs and spaces.

**Comment by friederbluemle** [comment]
The whitespace errors were automatically fixed by directly invoking `trailing_whitespace_fixer` from [pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks/)

**Comment by friederbluemle** [comment]
@neuberoliveira - Any other questions/concerns about this PR? Thanks!

**Comment by friederbluemle** [comment]
Hi @neuberoliveira - If you have a chance please check this PR. Thanks! :)

**Comment by neuberoliveira** [comment]
sorry for delay, hard times here. And many thanks for this cleanup, is somenthing i plan, but was procrastinating a lot, thanks again

**Comment by friederbluemle** [comment]
No worries @neuberoliveira - Hope all is well!
Thanks for merging! :+1:

**Pull request merged**
